version: 0.0
os: linux

files:             
  - source: webapi.jar
    destination: /var
  - source: cloudwatch-config.json
    destination: /opt
    
hooks:
  AfterInstall:
   - location: ./afterInstall.sh
     timeout: 180
     runas: centos
